# Generated by Django 3.0.4 on 2020-03-12 20:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["-created"], name="colony_visi_created_4357ec_idx"
            ),
        ),
    ]
