# Generated by Django 3.0.4 on 2020-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colony", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit", name="confidence", field=models.FloatField(default=0.0),
        ),
    ]
